import localFont from "next/font/local";
import "./globals.css";

const kanit = localFont({
  src: [
    {
      path: "../public/fonts/Kanit-ExtraLight.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../public/fonts/Kanit-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/Kanit-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Kanit-Italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/fonts/Kanit-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Kanit-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/Kanit-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/Kanit-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-kanit",
  display: "swap",
  fallback: ["system-ui", "sans-serif"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="th"
      className={`${kanit.className} ${kanit.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
