name: ERP Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - name: Install
        run: 
          cd /home/ChidchanunServer/AnuminowSolutionERPSystem
          git pull origin main 
          npm i
      
      - name: Build
        run: 
          cd /home/ChidchanunServer/AnuminowSolutionERPSystem
          npm run build

      - name: Restart
        run: |
          cd /home/ChidchanunServer/AnuminowSolutionERPSystem
          pm2 restart erp
